### ISSUE TITLE
Adalogger Hypnos DS3231 check

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#106] opened 2023-11-09 17:43 UTC
You need to have the external DS3231 featherwing attached in addition to the Adalogger M0 with SD on it to get the functions to work!
If the Hypnos library for Adalogger Requires Both the Adalogger AND the DS3231 - can we put a check function somewhere in there to throw an error and print it saying DS3231 Required for proper functionality?

**Comment by WL-Richards** [comment] 2023-11-16 16:58
We could do this alternatively, we just disable RTC-related features when using the Adalogger by default and then have the option to enable RTC features at a later time

**Comment by ZakaryW** [comment] 2023-12-19 22:34
Is this what you had in mind?

**Comment by WL-Richards** [comment] 2024-02-27 19:44
Closing as this is effectively a duplicate of #134

**Closed by WL-Richards** 2024-02-27 19:44 UTC
Labels: enhancement
